adding varaibles and tags
NightOwl998/terraform-aws-alpha pull request #5
Opened 2023-01-31 14:16 UTC by NightOwl998

2023-01-31 14:26 UTC, geoffrey1330 requested changes
some part of your code are not properly formatted could you please run `terraform fmt` to format your code and commit again so i can review again.

2023-02-01 12:18 UTC, geoffrey1330 requested changes

2023-02-01 12:18 UTC, geoffrey1330 commented on provider.tf
>  }
Add newline at the end of file.

2023-02-01 13:04 UTC, geoffrey1330 approved these changes

2023-02-01 13:04 UTC, NightOwl998 commented on provider.tf
>  }
added new line at EOF

2023-02-01 13:21 UTC, merged